# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CameraOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'zoom': 'float',
        'bearing': 'float',
        'pitch': 'float'
    }

    attribute_map = {
        'zoom': 'zoom',
        'bearing': 'bearing',
        'pitch': 'pitch'
    }

    def __init__(self, zoom=None, bearing=None, pitch=None):  # noqa: E501
        """CameraOptions - a model defined in Swagger"""  # noqa: E501
        self._zoom = None
        self._bearing = None
        self._pitch = None
        self.discriminator = None
        if zoom is not None:
            self.zoom = zoom
        if bearing is not None:
            self.bearing = bearing
        if pitch is not None:
            self.pitch = pitch

    @property
    def zoom(self):
        """Gets the zoom of this CameraOptions.  # noqa: E501


        :return: The zoom of this CameraOptions.  # noqa: E501
        :rtype: float
        """
        return self._zoom

    @zoom.setter
    def zoom(self, zoom):
        """Sets the zoom of this CameraOptions.


        :param zoom: The zoom of this CameraOptions.  # noqa: E501
        :type: float
        """

        self._zoom = zoom

    @property
    def bearing(self):
        """Gets the bearing of this CameraOptions.  # noqa: E501


        :return: The bearing of this CameraOptions.  # noqa: E501
        :rtype: float
        """
        return self._bearing

    @bearing.setter
    def bearing(self, bearing):
        """Sets the bearing of this CameraOptions.


        :param bearing: The bearing of this CameraOptions.  # noqa: E501
        :type: float
        """

        self._bearing = bearing

    @property
    def pitch(self):
        """Gets the pitch of this CameraOptions.  # noqa: E501


        :return: The pitch of this CameraOptions.  # noqa: E501
        :rtype: float
        """
        return self._pitch

    @pitch.setter
    def pitch(self, pitch):
        """Sets the pitch of this CameraOptions.


        :param pitch: The pitch of this CameraOptions.  # noqa: E501
        :type: float
        """

        self._pitch = pitch

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CameraOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CameraOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
