# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CartoVistaExceptionCodeEnum(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNKNOWN = "Unknown"
    OK = "OK"
    EXPIREDCLAIMSSTRUCTURE = "ExpiredClaimsStructure"
    INVALIDWEBSERVICEREQUEST = "InvalidWebServiceRequest"
    UNAUTHORIZED = "Unauthorized"
    FORBIDDEN = "Forbidden"
    ERROR = "Error"
    NOTFOUND = "NotFound"
    INVALIDFOLDERNAME = "InvalidFolderName"
    SYSTEMFOLDERNOTDELETABLE = "SystemFolderNotDeletable"
    FOLDERNOTEMPTY = "FolderNotEmpty"
    INVALIDUPLOADFORMAT = "InvalidUploadFormat"
    REDISERROR = "RedisError"
    REDISUNAVAILABLE = "RedisUnavailable"
    INVALIDFOLDER = "InvalidFolder"
    USERCREATEFAILED = "UserCreateFailed"
    USERUPDATEFAILED = "UserUpdateFailed"
    USERNAMEOREMAILALREADYEXISTS = "UsernameOrEmailAlreadyExists"
    USERUPDATENOTALLOWED = "UserUpdateNotAllowed"
    INVALIDEMAILADDRESS = "InvalidEmailAddress"
    GROUPCREATEFAILED = "GroupCreateFailed"
    GROUPUPDATEFAILED = "GroupUpdateFailed"
    GROUPNAMEALREADYEXISTS = "GroupNameAlreadyExists"
    GROUPNAMETOOLONG = "GroupNameTooLong"
    USERSNOTIMPORTABLE = "UsersNotImportable"
    GROUPSNOTIMPORTABLE = "GroupsNotImportable"
    INVALIDPROVIDER = "InvalidProvider"
    INVALIDEMAILDOMAIN = "InvalidEmailDomain"
    CANTCHANGEUSERSINACTIVEDIRECTORYGROUP = "CantChangeUsersInActiveDirectoryGroup"
    CANTREMOVELASTADMINISTRATOR = "CantRemoveLastAdministrator"
    NOTWHITELISTED = "NotWhitelisted"
    TENANTCREATEFAILED = "TenantCreateFailed"
    TENANTUPDATEFAILED = "TenantUpdateFailed"
    TENANTNAMEALREADYEXISTS = "TenantNameAlreadyExists"
    TENANTURLCODEINUSE = "TenantURLCodeInUse"
    TENANTISDELETED = "TenantIsDeleted"
    TENANTISLASTACTIVE = "TenantIsLastActive"
    TENANTDISCLAIMERCREATEFAILED = "TenantDisclaimerCreateFailed"
    TENANTDISCLAIMERUPDATEFAILED = "TenantDisclaimerUpdateFailed"
    TENANTDISCLAIMERGETFAILED = "TenantDisclaimerGetFailed"
    TENANTDISCLAIMERALREADYEXISTS = "TenantDisclaimerAlreadyExists"
    TENANTEMAILCREATEFAILED = "TenantEmailCreateFailed"
    TENANTEMAILUPDATEFAILED = "TenantEmailUpdateFailed"
    TENANTEMAILGETFAILED = "TenantEmailGetFailed"
    TENANTEMAILALREADYEXISTS = "TenantEmailAlreadyExists"
    TENANTSTORAGELIMITREACHED = "TenantStorageLimitReached"
    COMPANYNAMEEXISTSORISINVALID = "CompanyNameExistsOrIsInvalid"
    NOPERMISSIONS = "NoPermissions"
    PROTECTEDDATA = "ProtectedData"
    ENCRYPTIONERROR = "EncryptionError"
    LOGINFAILED = "LoginFailed"
    INACTIVETENANT = "InactiveTenant"
    INVALIDTENANTLICENSE = "InvalidTenantLicense"
    INVALIDTENANTSUBSCRIPTION = "InvalidTenantSubscription"
    INVALIDEMAILORPASSWORD = "InvalidEmailOrPassword"
    THEREISNOTENANTDEFINEDWITHNAME = "ThereIsNoTenantDefinedWithName"
    INVALIDRECAPTCHA = "InvalidReCaptcha"
    ACCOUNTISLOCKOUT = "AccountIsLockout"
    BLOCKEDIPADDRESS = "BlockedIpAddress"
    IPADDRESSNOTWHITELISTED = "IpAddressNotWhitelisted"
    INVALIDEXTERNALPROVIDERTOKEN = "InvalidExternalProviderToken"
    SIGNUPFAILED = "SignUpFailed"
    INVALIDLICENSE = "InvalidLicense"
    LICENSEEXPIRED = "LicenseExpired"
    NOTVALIDATED = "NotValidated"
    INVALIDSERIALCODE = "InvalidSerialCode"
    INVALIDSIGNATURE = "InvalidSignature"
    INVALIDMACHINECODE = "InvalidMachineCode"
    INVALIDUSAGEMODE = "InvalidUsageMode"
    ACTIVATIONFAILED = "ActivationFailed"
    DEACTIVATED = "Deactivated"
    INVALIDDOMAIN = "InvalidDomain"
    MAXNUMUSERS = "MaxNumUsers"
    FEATURELOCKED = "FeatureLocked"
    DATAUPLOADFAILED = "DataUploadFailed"
    CVWP_FIDFOUND = "CVWP_fidFound"
    NOTZIPFILE = "NotZipFile"
    NOSUPPORTEDFORMATINZIP = "NoSupportedFormatInZip"
    TOOMANYSUPPORTEDFORMATINZIP = "TooManySupportedFormatInZip"
    INVALIDZIPCONTENT = "invalidZipContent"
    INVALIDZIPCONTENTMISSINGINDEXHTML = "invalidZipContentMissingIndexHTML"
    MAPINFOEXTENDEDNOTSUPPORTED = "MapInfoExtendedNotSupported"
    MAPVERSIONNOTSUPPORTED = "MapVersionNotSupported"
    SETUNIQUECOLUMN = "SetUniqueColumn"
    COLUMNNOTUNIQUE = "ColumnNotUnique"
    GEOMETRYTYPENOTFOUND = "GeometryTypeNotFound"
    TOOLARGENUMBER = "TooLargeNumber"
    DUPLICATECOLUMNNAME = "DuplicateColumnName"
    NOSHEETS = "NoSheets"
    INVALIDVALUEFOUND = "InvalidValueFound"
    MISSINGFILESINZIP = "MissingFilesInZip"
    DEPRECATEDPROJECTION = "DeprecatedProjection"
    CVWP_COLUMNFOUND = "CVWP_ColumnFound"
    APPEND = "Append"
    DATAINUSE = "DataInUse"
    MUSTBETILED = "MustBeTiled"
    COLUMNCANTHAVEDUPLICATES = "ColumnCantHaveDuplicates"
    COLUMNTYPESMISMATCH = "ColumnTypesMismatch"
    COLUMNIDANDROWCOUNTNOTEQUAL = "ColumnIdAndRowCountNotEqual"
    CANTSETVALUEFORINTERNALCOLUMN = "CantSetValueForInternalColumn"
    COLUMNNOTINDATATABLE = "ColumnNotInDataTable"
    CANTSETDATETIMEASUNIQUECOLUMN = "CantSetDateTimeAsUniqueColumn"
    GETDATAROWERROR = "GetDataRowError"
    CANTDELETEUNIQUECOLUMN = "CantDeleteUniqueColumn"
    CANTCONVERTBETWEENDATETIMEANDNUMERIC = "CantConvertBetweenDateTimeAndNumeric"
    UPDATETYPEINVALIDDATA = "UpdateTypeInvalidData"
    UPDATETYPEINVALIDDATE = "UpdateTypeInvalidDate"
    INVALIDAGGREGATIONTYPE = "InvalidAggregationType"
    INVALIDEDITORMODE = "InvalidEditorMode"
    INVALIDDOMAINOFVALUESTYPE = "InvalidDomainOfValuesType"
    INVALIDCALCULATEDVALUES = "InvalidCalculatedValues"
    INVALIDDATAJOIN = "InvalidDataJoin"
    DATAJOINTARGETMUSTBEALAYER = "DataJoinTargetMustBeALayer"
    DATAJOINSOURCECANNOTBEALAYER = "DataJoinSourceCannotBeALayer"
    ONETOONEJOINHASMORELINKSTHANRECORDS = "OneToOneJoinHasMoreLinksThanRecords"
    JOINCOUNTISZERO = "JoinCountIsZero"
    INVALIDTIMESERIES = "InvalidTimeSeries"
    TIMESERIESCOLUMNMUSTBENUMBERORDATE = "TimeSeriesColumnMustBeNumberOrDate"
    TIMESERIESCOLUMNCANNOTBENULLWHENONETOMANYJOINSEXIST = "TimeSeriesColumnCannotBeNullWhenOneToManyJoinsExist"
    COLUMNUSEDINTIMESERIES = "ColumnUsedInTimeSeries"
    COLUMNUSEDINCALCULATEDVALUES = "ColumnUsedInCalculatedValues"
    GEOCODINGLIMITEXCEEDED = "GeocodingLimitExceeded"
    CANTDELETESOURCELAYER = "CantDeleteSourceLayer"
    CANTEDITDEMOLAYERDATA = "CantEditDemoLayerData"
    CANTMODIFYLAYERSOURCESTRUCTURE = "CantModifyLayerSourceStructure"
    INVALIDHEATMAPPARAMETERS = "InvalidHeatmapParameters"
    INVALIDHEATMAPRESOLUTION = "InvalidHeatmapResolution"
    HEATMAPALREADYGENERATED = "HeatmapAlreadyGenerated"
    HEATMAPSOURCECANNOTBECHANGED = "HeatmapSourceCannotBeChanged"
    HEATMAPISGENERATING = "HeatmapIsGenerating"
    INVALIDLATLONGDATA = "InvalidLatLongData"
    INVALIDDATACOLUMN = "InvalidDataColumn"
    INVALIDCALCULATEDEXPRESSION = "InvalidCalculatedExpression"
    EXPRESSIONISCALCULATING = "ExpressionIsCalculating"
    UNRECOGNIZEDPROJ4STRING = "UnrecognizedProj4String"
    QUADTREEINDEXNOTGENERATED = "QuadTreeIndexNotGenerated"
    INVALIDGEOMETRY = "InvalidGeometry"
    MAPUPLOADERROR = "MapUploadError"
    MAPINUSE = "MapInUse"
    MAPHASNONONTILEDSERVERLAYER = "MapHasNoNonTiledServerLayer"
    MAPMUSTBEDYNAMIC = "MapMustBeDynamic"
    LAYERFORMAPNOTFOUND = "LayerForMapNotFound"
    LAYERFORMAPEXCEEDSFEATURECOUNT = "LayerForMapExceedsFeatureCount"
    INVALIDISOCHRONERANGE = "InvalidIsochroneRange"
    INVALIDISOCHRONETRANSPORTTYPE = "InvalidIsochroneTransportType"
    SESSIONUPDATEFAILED = "SessionUpdateFailed"
    SESSIONCREATEFAILED = "SessionCreateFailed"
    SESSIONUNIQUECOLUMNCHANGED = "SessionUniqueColumnChanged"
    CANTDELETELASTSLIDE = "CantDeleteLastSlide"
    DATAQUERYMAXCOUNTEXCEEDED = "DataQueryMaxCountExceeded"
    IDENTIFIERALREADYINUSE = "IdentifierAlreadyInUse"
    IDENTIFIERCANNOTBENULL = "IdentifierCannotBeNull"
    NAMEALREADYINUSE = "NameAlreadyInUse"
    IDENTIFIERCONTAINSINVALIDCHARACTER = "IdentifierContainsInvalidCharacter"
    IDENTIFIERTOOLONG = "IdentifierTooLong"
    NAMETOOLONG = "NameTooLong"
    INVALIDGEOMETRYTYPE = "InvalidGeometryType"
    ROWCOUNTOUTSIDEOFRANGE = "RowCountOutsideOfRange"
    COLUMNUSEDINJOIN = "ColumnUsedInJoin"
    CREATEUPDATEFAILED = "CreateUpdateFailed"
    UNIQUECOLUMNREQUIRED = "UniqueColumnRequired"
    UNIQUECOLUMNMISSINGINLIST = "UniqueColumnMissingInList"
    DELETEFAILED = "DeleteFailed"
    EXTERNALLAYER = "ExternalLayer"
    MANAGEDTABLE = "ManagedTable"
    NOTEXTERNALLAYER = "NotExternalLayer"
    INVALIDEXTERNALLAYERURL = "InvalidExternalLayerUrl"
    INVALIDWMSVERSION = "InvalidWmsVersion"
    GRIDLAYERUPLOADFAILED = "GridLayerUploadFailed"
    PROJECTIONNOTFOUND = "ProjectionNotFound"
    CANTDELETELASTGRIDSOURCE = "CantDeleteLastGridSource"
    INVALIDGRIDLAYERREQUESTHEADERRANGE = "InvalidGridLayerRequestHeaderRange"
    CANNOTADDRGBTONUMERICGRIDLAYER = "CannotAddRGBToNumericGridLayer"
    CANNOTADDNUMERICTORGBGRIDLAYER = "CannotAddNumericToRGBGridLayer"
    SELECTIONTOOLARGE = "SelectionTooLarge"
    SELECTIONHASNOINTERSECTION = "SelectionHasNoIntersection"
    INVALIDINTERSECTION = "InvalidIntersection"
    VIEWCREATIONERROR = "ViewCreationError"
    COLUMNTYPENOTALLOWED = "ColumnTypeNotAllowed"
    VIEWEXPRESSIONCANNOTHAVEACOLUMN = "ViewExpressionCannotHaveAColumn"
    VIEWFROMCOLUMNMUSTHAVEACOLUMN = "ViewFromColumnMustHaveAColumn"
    VIEWUPDATEERROR = "ViewUpdateError"
    ONLYREADPERMISSIONONVIEWS = "OnlyReadPermissionOnViews"
    INVALIDVIEWEXPRESSION = "InvalidViewExpression"
    VIEWSMUSTDELETEDBEFORECREATINGNEWONES = "ViewsMustDeletedBeforeCreatingNewOnes"
    WEIGHTOUTOFBOUND = "WeightOutOfBound"
    VARIABLEUPDATEERROR = "VariableUpdateError"
    UPDATEVARIABLEFORBIDDEN = "UpdateVariableForbidden"
    LAYERUSEDINCOMPOSITESCORINGANALYSIS = "LayerUsedInCompositeScoringAnalysis"
    COLUMNUSEDINCOMPOSITESCORINGANALYSIS = "ColumnUsedInCompositeScoringAnalysis"
    VARIABLESCANNOTUSEONETOMANYJOINEDCOLUMNS = "VariablesCannotUseOneToManyJoinedColumns"
    MAXIMUMMAPS = "MaximumMaps"
    MAXIMUMLAYERSPERMAP = "MaximumLayersPerMap"
    MAPLOCKED = "MapLocked"
    INVALIDSYMBOL = "InvalidSymbol"
    POIISGENERATING = "PoiIsGenerating"
    INVALIDKVVALUES = "InvalidKvValues"
    INVALIDSCENARIOS = "InvalidScenarios"
    INVALIDNAME = "InvalidName"
    LAYERUSEDINPOIANALYSIS = "LayerUsedInPoiAnalysis"
    TABLEUSEDINPOIANALYSIS = "TableUsedInPoiAnalysis"
    COLUMNUSEDINPOIANALYSIS = "ColumnUsedInPoiAnalysis"
    NOANALYSISFOUND = "NoAnalysisFound"
    INVALIDUSERANALYSIS = "InvalidUserAnalysis"
    INVALIDANALYSIS = "InvalidAnalysis"
    INVALIDFOOTPRINTLAYER = "InvalidFootprintLayer"
    POIRASTERISGENERATING = "PoiRasterIsGenerating"
    BUFFEROUTOFRANGE = "BufferOutOfRange"
    MISSINGFOOTPRINTLAYER = "MissingFootprintLayer"
    INVALIDCOLUMNNAME = "InvalidColumnName"
    INVALIDMAPACTION = "InvalidMapAction"
    MAPACTIONFAILED = "MapActionFailed"
    AZUREMANAGEDIDENTITYACCESSTOKENFAILURE = "AzureManagedIdentityAccessTokenFailure"
    OAUTHERROR = "OAuthError"
    OAUTHINVALIDCLIENTID = "OAuthInvalidClientId"
    OAUTHINVALIDREDIRECTURI = "OAuthInvalidRedirectURI"
    OAUTHINVALIDREQUEST = "OAuthInvalidRequest"
    OAUTHUNSUPPORTEDRESPONSETYPE = "OAuthUnsupportedResponseType"
    OAUTHINVALIDSCOPE = "OAuthInvalidScope"
    OAUTHACCESSDENIED = "OAuthAccessDenied"
    OAUTHINVALIDGRANT = "OAuthInvalidGrant"
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """CartoVistaExceptionCodeEnum - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CartoVistaExceptionCodeEnum, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CartoVistaExceptionCodeEnum):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
