# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CustomPoiAnalysisWithNewId(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'new_analysis_id': 'str',
        'analyses': 'list[CustomPoiAnalysis]'
    }

    attribute_map = {
        'new_analysis_id': 'newAnalysisId',
        'analyses': 'analyses'
    }

    def __init__(self, new_analysis_id=None, analyses=None):  # noqa: E501
        """CustomPoiAnalysisWithNewId - a model defined in Swagger"""  # noqa: E501
        self._new_analysis_id = None
        self._analyses = None
        self.discriminator = None
        if new_analysis_id is not None:
            self.new_analysis_id = new_analysis_id
        if analyses is not None:
            self.analyses = analyses

    @property
    def new_analysis_id(self):
        """Gets the new_analysis_id of this CustomPoiAnalysisWithNewId.  # noqa: E501


        :return: The new_analysis_id of this CustomPoiAnalysisWithNewId.  # noqa: E501
        :rtype: str
        """
        return self._new_analysis_id

    @new_analysis_id.setter
    def new_analysis_id(self, new_analysis_id):
        """Sets the new_analysis_id of this CustomPoiAnalysisWithNewId.


        :param new_analysis_id: The new_analysis_id of this CustomPoiAnalysisWithNewId.  # noqa: E501
        :type: str
        """

        self._new_analysis_id = new_analysis_id

    @property
    def analyses(self):
        """Gets the analyses of this CustomPoiAnalysisWithNewId.  # noqa: E501


        :return: The analyses of this CustomPoiAnalysisWithNewId.  # noqa: E501
        :rtype: list[CustomPoiAnalysis]
        """
        return self._analyses

    @analyses.setter
    def analyses(self, analyses):
        """Sets the analyses of this CustomPoiAnalysisWithNewId.


        :param analyses: The analyses of this CustomPoiAnalysisWithNewId.  # noqa: E501
        :type: list[CustomPoiAnalysis]
        """

        self._analyses = analyses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomPoiAnalysisWithNewId, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomPoiAnalysisWithNewId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
