# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DemoMap(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'map_id': 'str',
        'layer_ids': 'list[str]',
        'grid_layer_ids': 'list[str]',
        'wmts_ids': 'list[str]',
        'wms_ids': 'list[str]',
        'title': 'str',
        'friendly_identifier': 'str',
        'industries': 'list[IndustryEnum]',
        'goals': 'list[GoalEnum]'
    }

    attribute_map = {
        'map_id': 'mapId',
        'layer_ids': 'layerIds',
        'grid_layer_ids': 'gridLayerIds',
        'wmts_ids': 'wmtsIds',
        'wms_ids': 'wmsIds',
        'title': 'title',
        'friendly_identifier': 'friendlyIdentifier',
        'industries': 'industries',
        'goals': 'goals'
    }

    def __init__(self, map_id=None, layer_ids=None, grid_layer_ids=None, wmts_ids=None, wms_ids=None, title=None, friendly_identifier=None, industries=None, goals=None):  # noqa: E501
        """DemoMap - a model defined in Swagger"""  # noqa: E501
        self._map_id = None
        self._layer_ids = None
        self._grid_layer_ids = None
        self._wmts_ids = None
        self._wms_ids = None
        self._title = None
        self._friendly_identifier = None
        self._industries = None
        self._goals = None
        self.discriminator = None
        if map_id is not None:
            self.map_id = map_id
        if layer_ids is not None:
            self.layer_ids = layer_ids
        if grid_layer_ids is not None:
            self.grid_layer_ids = grid_layer_ids
        if wmts_ids is not None:
            self.wmts_ids = wmts_ids
        if wms_ids is not None:
            self.wms_ids = wms_ids
        if title is not None:
            self.title = title
        if friendly_identifier is not None:
            self.friendly_identifier = friendly_identifier
        if industries is not None:
            self.industries = industries
        if goals is not None:
            self.goals = goals

    @property
    def map_id(self):
        """Gets the map_id of this DemoMap.  # noqa: E501


        :return: The map_id of this DemoMap.  # noqa: E501
        :rtype: str
        """
        return self._map_id

    @map_id.setter
    def map_id(self, map_id):
        """Sets the map_id of this DemoMap.


        :param map_id: The map_id of this DemoMap.  # noqa: E501
        :type: str
        """

        self._map_id = map_id

    @property
    def layer_ids(self):
        """Gets the layer_ids of this DemoMap.  # noqa: E501


        :return: The layer_ids of this DemoMap.  # noqa: E501
        :rtype: list[str]
        """
        return self._layer_ids

    @layer_ids.setter
    def layer_ids(self, layer_ids):
        """Sets the layer_ids of this DemoMap.


        :param layer_ids: The layer_ids of this DemoMap.  # noqa: E501
        :type: list[str]
        """

        self._layer_ids = layer_ids

    @property
    def grid_layer_ids(self):
        """Gets the grid_layer_ids of this DemoMap.  # noqa: E501


        :return: The grid_layer_ids of this DemoMap.  # noqa: E501
        :rtype: list[str]
        """
        return self._grid_layer_ids

    @grid_layer_ids.setter
    def grid_layer_ids(self, grid_layer_ids):
        """Sets the grid_layer_ids of this DemoMap.


        :param grid_layer_ids: The grid_layer_ids of this DemoMap.  # noqa: E501
        :type: list[str]
        """

        self._grid_layer_ids = grid_layer_ids

    @property
    def wmts_ids(self):
        """Gets the wmts_ids of this DemoMap.  # noqa: E501


        :return: The wmts_ids of this DemoMap.  # noqa: E501
        :rtype: list[str]
        """
        return self._wmts_ids

    @wmts_ids.setter
    def wmts_ids(self, wmts_ids):
        """Sets the wmts_ids of this DemoMap.


        :param wmts_ids: The wmts_ids of this DemoMap.  # noqa: E501
        :type: list[str]
        """

        self._wmts_ids = wmts_ids

    @property
    def wms_ids(self):
        """Gets the wms_ids of this DemoMap.  # noqa: E501


        :return: The wms_ids of this DemoMap.  # noqa: E501
        :rtype: list[str]
        """
        return self._wms_ids

    @wms_ids.setter
    def wms_ids(self, wms_ids):
        """Sets the wms_ids of this DemoMap.


        :param wms_ids: The wms_ids of this DemoMap.  # noqa: E501
        :type: list[str]
        """

        self._wms_ids = wms_ids

    @property
    def title(self):
        """Gets the title of this DemoMap.  # noqa: E501


        :return: The title of this DemoMap.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this DemoMap.


        :param title: The title of this DemoMap.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def friendly_identifier(self):
        """Gets the friendly_identifier of this DemoMap.  # noqa: E501


        :return: The friendly_identifier of this DemoMap.  # noqa: E501
        :rtype: str
        """
        return self._friendly_identifier

    @friendly_identifier.setter
    def friendly_identifier(self, friendly_identifier):
        """Sets the friendly_identifier of this DemoMap.


        :param friendly_identifier: The friendly_identifier of this DemoMap.  # noqa: E501
        :type: str
        """

        self._friendly_identifier = friendly_identifier

    @property
    def industries(self):
        """Gets the industries of this DemoMap.  # noqa: E501


        :return: The industries of this DemoMap.  # noqa: E501
        :rtype: list[IndustryEnum]
        """
        return self._industries

    @industries.setter
    def industries(self, industries):
        """Sets the industries of this DemoMap.


        :param industries: The industries of this DemoMap.  # noqa: E501
        :type: list[IndustryEnum]
        """

        self._industries = industries

    @property
    def goals(self):
        """Gets the goals of this DemoMap.  # noqa: E501


        :return: The goals of this DemoMap.  # noqa: E501
        :rtype: list[GoalEnum]
        """
        return self._goals

    @goals.setter
    def goals(self, goals):
        """Sets the goals of this DemoMap.


        :param goals: The goals of this DemoMap.  # noqa: E501
        :type: list[GoalEnum]
        """

        self._goals = goals

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DemoMap, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DemoMap):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
