# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GenericWebPortalResponseError(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'codes': 'list[str]',
        'code_details': 'str',
        'message': 'str',
        'additional_information': 'list[str]'
    }

    attribute_map = {
        'code': 'code',
        'codes': 'codes',
        'code_details': 'codeDetails',
        'message': 'message',
        'additional_information': 'additionalInformation'
    }

    def __init__(self, code=None, codes=None, code_details=None, message=None, additional_information=None):  # noqa: E501
        """GenericWebPortalResponseError - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._codes = None
        self._code_details = None
        self._message = None
        self._additional_information = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if codes is not None:
            self.codes = codes
        if code_details is not None:
            self.code_details = code_details
        if message is not None:
            self.message = message
        if additional_information is not None:
            self.additional_information = additional_information

    @property
    def code(self):
        """Gets the code of this GenericWebPortalResponseError.  # noqa: E501


        :return: The code of this GenericWebPortalResponseError.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this GenericWebPortalResponseError.


        :param code: The code of this GenericWebPortalResponseError.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def codes(self):
        """Gets the codes of this GenericWebPortalResponseError.  # noqa: E501


        :return: The codes of this GenericWebPortalResponseError.  # noqa: E501
        :rtype: list[str]
        """
        return self._codes

    @codes.setter
    def codes(self, codes):
        """Sets the codes of this GenericWebPortalResponseError.


        :param codes: The codes of this GenericWebPortalResponseError.  # noqa: E501
        :type: list[str]
        """

        self._codes = codes

    @property
    def code_details(self):
        """Gets the code_details of this GenericWebPortalResponseError.  # noqa: E501


        :return: The code_details of this GenericWebPortalResponseError.  # noqa: E501
        :rtype: str
        """
        return self._code_details

    @code_details.setter
    def code_details(self, code_details):
        """Sets the code_details of this GenericWebPortalResponseError.


        :param code_details: The code_details of this GenericWebPortalResponseError.  # noqa: E501
        :type: str
        """

        self._code_details = code_details

    @property
    def message(self):
        """Gets the message of this GenericWebPortalResponseError.  # noqa: E501


        :return: The message of this GenericWebPortalResponseError.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this GenericWebPortalResponseError.


        :param message: The message of this GenericWebPortalResponseError.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def additional_information(self):
        """Gets the additional_information of this GenericWebPortalResponseError.  # noqa: E501


        :return: The additional_information of this GenericWebPortalResponseError.  # noqa: E501
        :rtype: list[str]
        """
        return self._additional_information

    @additional_information.setter
    def additional_information(self, additional_information):
        """Sets the additional_information of this GenericWebPortalResponseError.


        :param additional_information: The additional_information of this GenericWebPortalResponseError.  # noqa: E501
        :type: list[str]
        """

        self._additional_information = additional_information

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenericWebPortalResponseError, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenericWebPortalResponseError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
