# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetFeatureIdsByStackParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stack': 'list[SelectionStackBaseDTOOfDataQueryColumnDTO]',
        'filter_data_columns': 'list[DataQueryColumnDTO]',
        'spatial_filter': 'OneOfGetFeatureIdsByStackParametersSpatialFilter'
    }

    attribute_map = {
        'stack': 'stack',
        'filter_data_columns': 'filterDataColumns',
        'spatial_filter': 'spatialFilter'
    }

    def __init__(self, stack=None, filter_data_columns=None, spatial_filter=None):  # noqa: E501
        """GetFeatureIdsByStackParameters - a model defined in Swagger"""  # noqa: E501
        self._stack = None
        self._filter_data_columns = None
        self._spatial_filter = None
        self.discriminator = None
        if stack is not None:
            self.stack = stack
        if filter_data_columns is not None:
            self.filter_data_columns = filter_data_columns
        if spatial_filter is not None:
            self.spatial_filter = spatial_filter

    @property
    def stack(self):
        """Gets the stack of this GetFeatureIdsByStackParameters.  # noqa: E501


        :return: The stack of this GetFeatureIdsByStackParameters.  # noqa: E501
        :rtype: list[SelectionStackBaseDTOOfDataQueryColumnDTO]
        """
        return self._stack

    @stack.setter
    def stack(self, stack):
        """Sets the stack of this GetFeatureIdsByStackParameters.


        :param stack: The stack of this GetFeatureIdsByStackParameters.  # noqa: E501
        :type: list[SelectionStackBaseDTOOfDataQueryColumnDTO]
        """

        self._stack = stack

    @property
    def filter_data_columns(self):
        """Gets the filter_data_columns of this GetFeatureIdsByStackParameters.  # noqa: E501


        :return: The filter_data_columns of this GetFeatureIdsByStackParameters.  # noqa: E501
        :rtype: list[DataQueryColumnDTO]
        """
        return self._filter_data_columns

    @filter_data_columns.setter
    def filter_data_columns(self, filter_data_columns):
        """Sets the filter_data_columns of this GetFeatureIdsByStackParameters.


        :param filter_data_columns: The filter_data_columns of this GetFeatureIdsByStackParameters.  # noqa: E501
        :type: list[DataQueryColumnDTO]
        """

        self._filter_data_columns = filter_data_columns

    @property
    def spatial_filter(self):
        """Gets the spatial_filter of this GetFeatureIdsByStackParameters.  # noqa: E501


        :return: The spatial_filter of this GetFeatureIdsByStackParameters.  # noqa: E501
        :rtype: OneOfGetFeatureIdsByStackParametersSpatialFilter
        """
        return self._spatial_filter

    @spatial_filter.setter
    def spatial_filter(self, spatial_filter):
        """Sets the spatial_filter of this GetFeatureIdsByStackParameters.


        :param spatial_filter: The spatial_filter of this GetFeatureIdsByStackParameters.  # noqa: E501
        :type: OneOfGetFeatureIdsByStackParametersSpatialFilter
        """

        self._spatial_filter = spatial_filter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetFeatureIdsByStackParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetFeatureIdsByStackParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
