# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetStatisticsParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'search_criteria': 'str',
        'pagination': 'OneOfGetStatisticsParametersPagination',
        'sort': 'OneOfGetStatisticsParametersSort',
        'filters': 'dict(str, object)'
    }

    attribute_map = {
        'search_criteria': 'searchCriteria',
        'pagination': 'pagination',
        'sort': 'sort',
        'filters': 'filters'
    }

    def __init__(self, search_criteria=None, pagination=None, sort=None, filters=None):  # noqa: E501
        """GetStatisticsParameters - a model defined in Swagger"""  # noqa: E501
        self._search_criteria = None
        self._pagination = None
        self._sort = None
        self._filters = None
        self.discriminator = None
        if search_criteria is not None:
            self.search_criteria = search_criteria
        if pagination is not None:
            self.pagination = pagination
        if sort is not None:
            self.sort = sort
        if filters is not None:
            self.filters = filters

    @property
    def search_criteria(self):
        """Gets the search_criteria of this GetStatisticsParameters.  # noqa: E501


        :return: The search_criteria of this GetStatisticsParameters.  # noqa: E501
        :rtype: str
        """
        return self._search_criteria

    @search_criteria.setter
    def search_criteria(self, search_criteria):
        """Sets the search_criteria of this GetStatisticsParameters.


        :param search_criteria: The search_criteria of this GetStatisticsParameters.  # noqa: E501
        :type: str
        """

        self._search_criteria = search_criteria

    @property
    def pagination(self):
        """Gets the pagination of this GetStatisticsParameters.  # noqa: E501


        :return: The pagination of this GetStatisticsParameters.  # noqa: E501
        :rtype: OneOfGetStatisticsParametersPagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this GetStatisticsParameters.


        :param pagination: The pagination of this GetStatisticsParameters.  # noqa: E501
        :type: OneOfGetStatisticsParametersPagination
        """

        self._pagination = pagination

    @property
    def sort(self):
        """Gets the sort of this GetStatisticsParameters.  # noqa: E501


        :return: The sort of this GetStatisticsParameters.  # noqa: E501
        :rtype: OneOfGetStatisticsParametersSort
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this GetStatisticsParameters.


        :param sort: The sort of this GetStatisticsParameters.  # noqa: E501
        :type: OneOfGetStatisticsParametersSort
        """

        self._sort = sort

    @property
    def filters(self):
        """Gets the filters of this GetStatisticsParameters.  # noqa: E501


        :return: The filters of this GetStatisticsParameters.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._filters

    @filters.setter
    def filters(self, filters):
        """Sets the filters of this GetStatisticsParameters.


        :param filters: The filters of this GetStatisticsParameters.  # noqa: E501
        :type: dict(str, object)
        """

        self._filters = filters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetStatisticsParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetStatisticsParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
