# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GridLayerSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'grid_layer_id': 'str',
        'map_id': 'str',
        'alias': 'str',
        'style': 'GridLayerSettingsStyle',
        'rendering': 'LayerSettingsRendering',
        'visibility_ranges': 'GridLayerSettingsVisibilityRanges',
        'legend': 'LayerSettingsLegend'
    }

    attribute_map = {
        'id': 'id',
        'grid_layer_id': 'gridLayerId',
        'map_id': 'mapId',
        'alias': 'alias',
        'style': 'style',
        'rendering': 'rendering',
        'visibility_ranges': 'visibilityRanges',
        'legend': 'legend'
    }

    def __init__(self, id=None, grid_layer_id=None, map_id=None, alias=None, style=None, rendering=None, visibility_ranges=None, legend=None):  # noqa: E501
        """GridLayerSettings - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._grid_layer_id = None
        self._map_id = None
        self._alias = None
        self._style = None
        self._rendering = None
        self._visibility_ranges = None
        self._legend = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if grid_layer_id is not None:
            self.grid_layer_id = grid_layer_id
        if map_id is not None:
            self.map_id = map_id
        if alias is not None:
            self.alias = alias
        if style is not None:
            self.style = style
        if rendering is not None:
            self.rendering = rendering
        if visibility_ranges is not None:
            self.visibility_ranges = visibility_ranges
        if legend is not None:
            self.legend = legend

    @property
    def id(self):
        """Gets the id of this GridLayerSettings.  # noqa: E501


        :return: The id of this GridLayerSettings.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GridLayerSettings.


        :param id: The id of this GridLayerSettings.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def grid_layer_id(self):
        """Gets the grid_layer_id of this GridLayerSettings.  # noqa: E501


        :return: The grid_layer_id of this GridLayerSettings.  # noqa: E501
        :rtype: str
        """
        return self._grid_layer_id

    @grid_layer_id.setter
    def grid_layer_id(self, grid_layer_id):
        """Sets the grid_layer_id of this GridLayerSettings.


        :param grid_layer_id: The grid_layer_id of this GridLayerSettings.  # noqa: E501
        :type: str
        """

        self._grid_layer_id = grid_layer_id

    @property
    def map_id(self):
        """Gets the map_id of this GridLayerSettings.  # noqa: E501


        :return: The map_id of this GridLayerSettings.  # noqa: E501
        :rtype: str
        """
        return self._map_id

    @map_id.setter
    def map_id(self, map_id):
        """Sets the map_id of this GridLayerSettings.


        :param map_id: The map_id of this GridLayerSettings.  # noqa: E501
        :type: str
        """

        self._map_id = map_id

    @property
    def alias(self):
        """Gets the alias of this GridLayerSettings.  # noqa: E501


        :return: The alias of this GridLayerSettings.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this GridLayerSettings.


        :param alias: The alias of this GridLayerSettings.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def style(self):
        """Gets the style of this GridLayerSettings.  # noqa: E501


        :return: The style of this GridLayerSettings.  # noqa: E501
        :rtype: GridLayerSettingsStyle
        """
        return self._style

    @style.setter
    def style(self, style):
        """Sets the style of this GridLayerSettings.


        :param style: The style of this GridLayerSettings.  # noqa: E501
        :type: GridLayerSettingsStyle
        """

        self._style = style

    @property
    def rendering(self):
        """Gets the rendering of this GridLayerSettings.  # noqa: E501


        :return: The rendering of this GridLayerSettings.  # noqa: E501
        :rtype: LayerSettingsRendering
        """
        return self._rendering

    @rendering.setter
    def rendering(self, rendering):
        """Sets the rendering of this GridLayerSettings.


        :param rendering: The rendering of this GridLayerSettings.  # noqa: E501
        :type: LayerSettingsRendering
        """

        self._rendering = rendering

    @property
    def visibility_ranges(self):
        """Gets the visibility_ranges of this GridLayerSettings.  # noqa: E501


        :return: The visibility_ranges of this GridLayerSettings.  # noqa: E501
        :rtype: GridLayerSettingsVisibilityRanges
        """
        return self._visibility_ranges

    @visibility_ranges.setter
    def visibility_ranges(self, visibility_ranges):
        """Sets the visibility_ranges of this GridLayerSettings.


        :param visibility_ranges: The visibility_ranges of this GridLayerSettings.  # noqa: E501
        :type: GridLayerSettingsVisibilityRanges
        """

        self._visibility_ranges = visibility_ranges

    @property
    def legend(self):
        """Gets the legend of this GridLayerSettings.  # noqa: E501


        :return: The legend of this GridLayerSettings.  # noqa: E501
        :rtype: LayerSettingsLegend
        """
        return self._legend

    @legend.setter
    def legend(self, legend):
        """Sets the legend of this GridLayerSettings.


        :param legend: The legend of this GridLayerSettings.  # noqa: E501
        :type: LayerSettingsLegend
        """

        self._legend = legend

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GridLayerSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GridLayerSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
