# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InterfaceSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sidebar': 'SidebarSettings',
        'topbar': 'TopbarSettings'
    }

    attribute_map = {
        'sidebar': 'sidebar',
        'topbar': 'topbar'
    }

    def __init__(self, sidebar=None, topbar=None):  # noqa: E501
        """InterfaceSettings - a model defined in Swagger"""  # noqa: E501
        self._sidebar = None
        self._topbar = None
        self.discriminator = None
        if sidebar is not None:
            self.sidebar = sidebar
        if topbar is not None:
            self.topbar = topbar

    @property
    def sidebar(self):
        """Gets the sidebar of this InterfaceSettings.  # noqa: E501


        :return: The sidebar of this InterfaceSettings.  # noqa: E501
        :rtype: SidebarSettings
        """
        return self._sidebar

    @sidebar.setter
    def sidebar(self, sidebar):
        """Sets the sidebar of this InterfaceSettings.


        :param sidebar: The sidebar of this InterfaceSettings.  # noqa: E501
        :type: SidebarSettings
        """

        self._sidebar = sidebar

    @property
    def topbar(self):
        """Gets the topbar of this InterfaceSettings.  # noqa: E501


        :return: The topbar of this InterfaceSettings.  # noqa: E501
        :rtype: TopbarSettings
        """
        return self._topbar

    @topbar.setter
    def topbar(self, topbar):
        """Sets the topbar of this InterfaceSettings.


        :param topbar: The topbar of this InterfaceSettings.  # noqa: E501
        :type: TopbarSettings
        """

        self._topbar = topbar

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InterfaceSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InterfaceSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
