# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JoinCount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_valid_join': 'bool',
        'is_one_to_many': 'bool',
        'count': 'int'
    }

    attribute_map = {
        'is_valid_join': 'isValidJoin',
        'is_one_to_many': 'isOneToMany',
        'count': 'count'
    }

    def __init__(self, is_valid_join=None, is_one_to_many=None, count=None):  # noqa: E501
        """JoinCount - a model defined in Swagger"""  # noqa: E501
        self._is_valid_join = None
        self._is_one_to_many = None
        self._count = None
        self.discriminator = None
        if is_valid_join is not None:
            self.is_valid_join = is_valid_join
        if is_one_to_many is not None:
            self.is_one_to_many = is_one_to_many
        if count is not None:
            self.count = count

    @property
    def is_valid_join(self):
        """Gets the is_valid_join of this JoinCount.  # noqa: E501


        :return: The is_valid_join of this JoinCount.  # noqa: E501
        :rtype: bool
        """
        return self._is_valid_join

    @is_valid_join.setter
    def is_valid_join(self, is_valid_join):
        """Sets the is_valid_join of this JoinCount.


        :param is_valid_join: The is_valid_join of this JoinCount.  # noqa: E501
        :type: bool
        """

        self._is_valid_join = is_valid_join

    @property
    def is_one_to_many(self):
        """Gets the is_one_to_many of this JoinCount.  # noqa: E501


        :return: The is_one_to_many of this JoinCount.  # noqa: E501
        :rtype: bool
        """
        return self._is_one_to_many

    @is_one_to_many.setter
    def is_one_to_many(self, is_one_to_many):
        """Sets the is_one_to_many of this JoinCount.


        :param is_one_to_many: The is_one_to_many of this JoinCount.  # noqa: E501
        :type: bool
        """

        self._is_one_to_many = is_one_to_many

    @property
    def count(self):
        """Gets the count of this JoinCount.  # noqa: E501


        :return: The count of this JoinCount.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this JoinCount.


        :param count: The count of this JoinCount.  # noqa: E501
        :type: int
        """

        self._count = count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JoinCount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JoinCount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
