# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Oauth2TokenBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'grant_type': 'str',
        'code': 'str',
        'redirect_uri': 'str',
        'client_id': 'str',
        'code_verifier': 'str',
        'refresh_token': 'str'
    }

    attribute_map = {
        'grant_type': 'grant_type',
        'code': 'code',
        'redirect_uri': 'redirect_uri',
        'client_id': 'client_id',
        'code_verifier': 'code_verifier',
        'refresh_token': 'refresh_token'
    }

    def __init__(self, grant_type=None, code=None, redirect_uri=None, client_id=None, code_verifier=None, refresh_token=None):  # noqa: E501
        """Oauth2TokenBody - a model defined in Swagger"""  # noqa: E501
        self._grant_type = None
        self._code = None
        self._redirect_uri = None
        self._client_id = None
        self._code_verifier = None
        self._refresh_token = None
        self.discriminator = None
        if grant_type is not None:
            self.grant_type = grant_type
        if code is not None:
            self.code = code
        if redirect_uri is not None:
            self.redirect_uri = redirect_uri
        if client_id is not None:
            self.client_id = client_id
        if code_verifier is not None:
            self.code_verifier = code_verifier
        if refresh_token is not None:
            self.refresh_token = refresh_token

    @property
    def grant_type(self):
        """Gets the grant_type of this Oauth2TokenBody.  # noqa: E501


        :return: The grant_type of this Oauth2TokenBody.  # noqa: E501
        :rtype: str
        """
        return self._grant_type

    @grant_type.setter
    def grant_type(self, grant_type):
        """Sets the grant_type of this Oauth2TokenBody.


        :param grant_type: The grant_type of this Oauth2TokenBody.  # noqa: E501
        :type: str
        """

        self._grant_type = grant_type

    @property
    def code(self):
        """Gets the code of this Oauth2TokenBody.  # noqa: E501


        :return: The code of this Oauth2TokenBody.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Oauth2TokenBody.


        :param code: The code of this Oauth2TokenBody.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def redirect_uri(self):
        """Gets the redirect_uri of this Oauth2TokenBody.  # noqa: E501


        :return: The redirect_uri of this Oauth2TokenBody.  # noqa: E501
        :rtype: str
        """
        return self._redirect_uri

    @redirect_uri.setter
    def redirect_uri(self, redirect_uri):
        """Sets the redirect_uri of this Oauth2TokenBody.


        :param redirect_uri: The redirect_uri of this Oauth2TokenBody.  # noqa: E501
        :type: str
        """

        self._redirect_uri = redirect_uri

    @property
    def client_id(self):
        """Gets the client_id of this Oauth2TokenBody.  # noqa: E501


        :return: The client_id of this Oauth2TokenBody.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this Oauth2TokenBody.


        :param client_id: The client_id of this Oauth2TokenBody.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    @property
    def code_verifier(self):
        """Gets the code_verifier of this Oauth2TokenBody.  # noqa: E501


        :return: The code_verifier of this Oauth2TokenBody.  # noqa: E501
        :rtype: str
        """
        return self._code_verifier

    @code_verifier.setter
    def code_verifier(self, code_verifier):
        """Sets the code_verifier of this Oauth2TokenBody.


        :param code_verifier: The code_verifier of this Oauth2TokenBody.  # noqa: E501
        :type: str
        """

        self._code_verifier = code_verifier

    @property
    def refresh_token(self):
        """Gets the refresh_token of this Oauth2TokenBody.  # noqa: E501


        :return: The refresh_token of this Oauth2TokenBody.  # noqa: E501
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token):
        """Sets the refresh_token of this Oauth2TokenBody.


        :param refresh_token: The refresh_token of this Oauth2TokenBody.  # noqa: E501
        :type: str
        """

        self._refresh_token = refresh_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Oauth2TokenBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Oauth2TokenBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
