# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SetProviderParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'provider': 'SecurityProvider',
        'email': 'str',
        'provider_id': 'str'
    }

    attribute_map = {
        'provider': 'provider',
        'email': 'email',
        'provider_id': 'providerId'
    }

    def __init__(self, provider=None, email=None, provider_id=None):  # noqa: E501
        """SetProviderParameter - a model defined in Swagger"""  # noqa: E501
        self._provider = None
        self._email = None
        self._provider_id = None
        self.discriminator = None
        if provider is not None:
            self.provider = provider
        if email is not None:
            self.email = email
        if provider_id is not None:
            self.provider_id = provider_id

    @property
    def provider(self):
        """Gets the provider of this SetProviderParameter.  # noqa: E501


        :return: The provider of this SetProviderParameter.  # noqa: E501
        :rtype: SecurityProvider
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this SetProviderParameter.


        :param provider: The provider of this SetProviderParameter.  # noqa: E501
        :type: SecurityProvider
        """

        self._provider = provider

    @property
    def email(self):
        """Gets the email of this SetProviderParameter.  # noqa: E501


        :return: The email of this SetProviderParameter.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this SetProviderParameter.


        :param email: The email of this SetProviderParameter.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def provider_id(self):
        """Gets the provider_id of this SetProviderParameter.  # noqa: E501


        :return: The provider_id of this SetProviderParameter.  # noqa: E501
        :rtype: str
        """
        return self._provider_id

    @provider_id.setter
    def provider_id(self, provider_id):
        """Sets the provider_id of this SetProviderParameter.


        :param provider_id: The provider_id of this SetProviderParameter.  # noqa: E501
        :type: str
        """

        self._provider_id = provider_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SetProviderParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SetProviderParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
