# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShareMapExternalParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'emails': 'list[str]',
        'make_public': 'bool'
    }

    attribute_map = {
        'emails': 'emails',
        'make_public': 'makePublic'
    }

    def __init__(self, emails=None, make_public=None):  # noqa: E501
        """ShareMapExternalParameter - a model defined in Swagger"""  # noqa: E501
        self._emails = None
        self._make_public = None
        self.discriminator = None
        if emails is not None:
            self.emails = emails
        if make_public is not None:
            self.make_public = make_public

    @property
    def emails(self):
        """Gets the emails of this ShareMapExternalParameter.  # noqa: E501


        :return: The emails of this ShareMapExternalParameter.  # noqa: E501
        :rtype: list[str]
        """
        return self._emails

    @emails.setter
    def emails(self, emails):
        """Sets the emails of this ShareMapExternalParameter.


        :param emails: The emails of this ShareMapExternalParameter.  # noqa: E501
        :type: list[str]
        """

        self._emails = emails

    @property
    def make_public(self):
        """Gets the make_public of this ShareMapExternalParameter.  # noqa: E501


        :return: The make_public of this ShareMapExternalParameter.  # noqa: E501
        :rtype: bool
        """
        return self._make_public

    @make_public.setter
    def make_public(self, make_public):
        """Sets the make_public of this ShareMapExternalParameter.


        :param make_public: The make_public of this ShareMapExternalParameter.  # noqa: E501
        :type: bool
        """

        self._make_public = make_public

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShareMapExternalParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShareMapExternalParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
