# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SidebarSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'collapsed': 'bool',
        'components': 'PropertiesOfBoolean'
    }

    attribute_map = {
        'collapsed': 'collapsed',
        'components': 'components'
    }

    def __init__(self, collapsed=None, components=None):  # noqa: E501
        """SidebarSettings - a model defined in Swagger"""  # noqa: E501
        self._collapsed = None
        self._components = None
        self.discriminator = None
        if collapsed is not None:
            self.collapsed = collapsed
        if components is not None:
            self.components = components

    @property
    def collapsed(self):
        """Gets the collapsed of this SidebarSettings.  # noqa: E501


        :return: The collapsed of this SidebarSettings.  # noqa: E501
        :rtype: bool
        """
        return self._collapsed

    @collapsed.setter
    def collapsed(self, collapsed):
        """Sets the collapsed of this SidebarSettings.


        :param collapsed: The collapsed of this SidebarSettings.  # noqa: E501
        :type: bool
        """

        self._collapsed = collapsed

    @property
    def components(self):
        """Gets the components of this SidebarSettings.  # noqa: E501


        :return: The components of this SidebarSettings.  # noqa: E501
        :rtype: PropertiesOfBoolean
        """
        return self._components

    @components.setter
    def components(self, components):
        """Sets the components of this SidebarSettings.


        :param components: The components of this SidebarSettings.  # noqa: E501
        :type: PropertiesOfBoolean
        """

        self._components = components

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SidebarSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SidebarSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
