# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SlideItems(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hierarchy': 'list[SlideItemReference]',
        'slide_folders': 'dict(str, SlideFolder)',
        'slides': 'dict(str, Slide)'
    }

    attribute_map = {
        'hierarchy': 'hierarchy',
        'slide_folders': 'slideFolders',
        'slides': 'slides'
    }

    def __init__(self, hierarchy=None, slide_folders=None, slides=None):  # noqa: E501
        """SlideItems - a model defined in Swagger"""  # noqa: E501
        self._hierarchy = None
        self._slide_folders = None
        self._slides = None
        self.discriminator = None
        if hierarchy is not None:
            self.hierarchy = hierarchy
        if slide_folders is not None:
            self.slide_folders = slide_folders
        if slides is not None:
            self.slides = slides

    @property
    def hierarchy(self):
        """Gets the hierarchy of this SlideItems.  # noqa: E501


        :return: The hierarchy of this SlideItems.  # noqa: E501
        :rtype: list[SlideItemReference]
        """
        return self._hierarchy

    @hierarchy.setter
    def hierarchy(self, hierarchy):
        """Sets the hierarchy of this SlideItems.


        :param hierarchy: The hierarchy of this SlideItems.  # noqa: E501
        :type: list[SlideItemReference]
        """

        self._hierarchy = hierarchy

    @property
    def slide_folders(self):
        """Gets the slide_folders of this SlideItems.  # noqa: E501


        :return: The slide_folders of this SlideItems.  # noqa: E501
        :rtype: dict(str, SlideFolder)
        """
        return self._slide_folders

    @slide_folders.setter
    def slide_folders(self, slide_folders):
        """Sets the slide_folders of this SlideItems.


        :param slide_folders: The slide_folders of this SlideItems.  # noqa: E501
        :type: dict(str, SlideFolder)
        """

        self._slide_folders = slide_folders

    @property
    def slides(self):
        """Gets the slides of this SlideItems.  # noqa: E501


        :return: The slides of this SlideItems.  # noqa: E501
        :rtype: dict(str, Slide)
        """
        return self._slides

    @slides.setter
    def slides(self, slides):
        """Sets the slides of this SlideItems.


        :param slides: The slides of this SlideItems.  # noqa: E501
        :type: dict(str, Slide)
        """

        self._slides = slides

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SlideItems, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SlideItems):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
