# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SlideItemReference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'item_id': 'str',
        'is_folder': 'bool',
        'children': 'list[SlideItemReference]'
    }

    attribute_map = {
        'item_id': 'itemId',
        'is_folder': 'isFolder',
        'children': 'children'
    }

    def __init__(self, item_id=None, is_folder=None, children=None):  # noqa: E501
        """SlideItemReference - a model defined in Swagger"""  # noqa: E501
        self._item_id = None
        self._is_folder = None
        self._children = None
        self.discriminator = None
        if item_id is not None:
            self.item_id = item_id
        if is_folder is not None:
            self.is_folder = is_folder
        if children is not None:
            self.children = children

    @property
    def item_id(self):
        """Gets the item_id of this SlideItemReference.  # noqa: E501


        :return: The item_id of this SlideItemReference.  # noqa: E501
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this SlideItemReference.


        :param item_id: The item_id of this SlideItemReference.  # noqa: E501
        :type: str
        """

        self._item_id = item_id

    @property
    def is_folder(self):
        """Gets the is_folder of this SlideItemReference.  # noqa: E501


        :return: The is_folder of this SlideItemReference.  # noqa: E501
        :rtype: bool
        """
        return self._is_folder

    @is_folder.setter
    def is_folder(self, is_folder):
        """Sets the is_folder of this SlideItemReference.


        :param is_folder: The is_folder of this SlideItemReference.  # noqa: E501
        :type: bool
        """

        self._is_folder = is_folder

    @property
    def children(self):
        """Gets the children of this SlideItemReference.  # noqa: E501


        :return: The children of this SlideItemReference.  # noqa: E501
        :rtype: list[SlideItemReference]
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this SlideItemReference.


        :param children: The children of this SlideItemReference.  # noqa: E501
        :type: list[SlideItemReference]
        """

        self._children = children

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SlideItemReference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SlideItemReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
