# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TemporaryAnalysisMask(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'feature_id': 'str',
        'scenario_id': 'str'
    }

    attribute_map = {
        'feature_id': 'featureId',
        'scenario_id': 'scenarioId'
    }

    def __init__(self, feature_id=None, scenario_id=None):  # noqa: E501
        """TemporaryAnalysisMask - a model defined in Swagger"""  # noqa: E501
        self._feature_id = None
        self._scenario_id = None
        self.discriminator = None
        if feature_id is not None:
            self.feature_id = feature_id
        if scenario_id is not None:
            self.scenario_id = scenario_id

    @property
    def feature_id(self):
        """Gets the feature_id of this TemporaryAnalysisMask.  # noqa: E501


        :return: The feature_id of this TemporaryAnalysisMask.  # noqa: E501
        :rtype: str
        """
        return self._feature_id

    @feature_id.setter
    def feature_id(self, feature_id):
        """Sets the feature_id of this TemporaryAnalysisMask.


        :param feature_id: The feature_id of this TemporaryAnalysisMask.  # noqa: E501
        :type: str
        """

        self._feature_id = feature_id

    @property
    def scenario_id(self):
        """Gets the scenario_id of this TemporaryAnalysisMask.  # noqa: E501


        :return: The scenario_id of this TemporaryAnalysisMask.  # noqa: E501
        :rtype: str
        """
        return self._scenario_id

    @scenario_id.setter
    def scenario_id(self, scenario_id):
        """Sets the scenario_id of this TemporaryAnalysisMask.


        :param scenario_id: The scenario_id of this TemporaryAnalysisMask.  # noqa: E501
        :type: str
        """

        self._scenario_id = scenario_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TemporaryAnalysisMask, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TemporaryAnalysisMask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
