# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TransferMapsParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'map_ids': 'list[str]',
        'owner_id': 'str'
    }

    attribute_map = {
        'map_ids': 'mapIds',
        'owner_id': 'ownerId'
    }

    def __init__(self, map_ids=None, owner_id=None):  # noqa: E501
        """TransferMapsParameter - a model defined in Swagger"""  # noqa: E501
        self._map_ids = None
        self._owner_id = None
        self.discriminator = None
        if map_ids is not None:
            self.map_ids = map_ids
        if owner_id is not None:
            self.owner_id = owner_id

    @property
    def map_ids(self):
        """Gets the map_ids of this TransferMapsParameter.  # noqa: E501


        :return: The map_ids of this TransferMapsParameter.  # noqa: E501
        :rtype: list[str]
        """
        return self._map_ids

    @map_ids.setter
    def map_ids(self, map_ids):
        """Sets the map_ids of this TransferMapsParameter.


        :param map_ids: The map_ids of this TransferMapsParameter.  # noqa: E501
        :type: list[str]
        """

        self._map_ids = map_ids

    @property
    def owner_id(self):
        """Gets the owner_id of this TransferMapsParameter.  # noqa: E501


        :return: The owner_id of this TransferMapsParameter.  # noqa: E501
        :rtype: str
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """Sets the owner_id of this TransferMapsParameter.


        :param owner_id: The owner_id of this TransferMapsParameter.  # noqa: E501
        :type: str
        """

        self._owner_id = owner_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransferMapsParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransferMapsParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
