# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateWmsSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alias': 'str',
        'rendering': 'LayerSettingsRendering',
        'visibility_ranges': 'WmsSettingsVisibilityRanges',
        'legend': 'LayerSettingsLegend'
    }

    attribute_map = {
        'alias': 'alias',
        'rendering': 'rendering',
        'visibility_ranges': 'visibilityRanges',
        'legend': 'legend'
    }

    def __init__(self, alias=None, rendering=None, visibility_ranges=None, legend=None):  # noqa: E501
        """UpdateWmsSettings - a model defined in Swagger"""  # noqa: E501
        self._alias = None
        self._rendering = None
        self._visibility_ranges = None
        self._legend = None
        self.discriminator = None
        if alias is not None:
            self.alias = alias
        if rendering is not None:
            self.rendering = rendering
        if visibility_ranges is not None:
            self.visibility_ranges = visibility_ranges
        if legend is not None:
            self.legend = legend

    @property
    def alias(self):
        """Gets the alias of this UpdateWmsSettings.  # noqa: E501


        :return: The alias of this UpdateWmsSettings.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this UpdateWmsSettings.


        :param alias: The alias of this UpdateWmsSettings.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def rendering(self):
        """Gets the rendering of this UpdateWmsSettings.  # noqa: E501


        :return: The rendering of this UpdateWmsSettings.  # noqa: E501
        :rtype: LayerSettingsRendering
        """
        return self._rendering

    @rendering.setter
    def rendering(self, rendering):
        """Sets the rendering of this UpdateWmsSettings.


        :param rendering: The rendering of this UpdateWmsSettings.  # noqa: E501
        :type: LayerSettingsRendering
        """

        self._rendering = rendering

    @property
    def visibility_ranges(self):
        """Gets the visibility_ranges of this UpdateWmsSettings.  # noqa: E501


        :return: The visibility_ranges of this UpdateWmsSettings.  # noqa: E501
        :rtype: WmsSettingsVisibilityRanges
        """
        return self._visibility_ranges

    @visibility_ranges.setter
    def visibility_ranges(self, visibility_ranges):
        """Sets the visibility_ranges of this UpdateWmsSettings.


        :param visibility_ranges: The visibility_ranges of this UpdateWmsSettings.  # noqa: E501
        :type: WmsSettingsVisibilityRanges
        """

        self._visibility_ranges = visibility_ranges

    @property
    def legend(self):
        """Gets the legend of this UpdateWmsSettings.  # noqa: E501


        :return: The legend of this UpdateWmsSettings.  # noqa: E501
        :rtype: LayerSettingsLegend
        """
        return self._legend

    @legend.setter
    def legend(self, legend):
        """Sets the legend of this UpdateWmsSettings.


        :param legend: The legend of this UpdateWmsSettings.  # noqa: E501
        :type: LayerSettingsLegend
        """

        self._legend = legend

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateWmsSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateWmsSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
