# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserGroupPermission(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'permission_type': 'GenericPermissions',
        'security_identity': 'str'
    }

    attribute_map = {
        'permission_type': 'permissionType',
        'security_identity': 'securityIdentity'
    }

    def __init__(self, permission_type=None, security_identity=None):  # noqa: E501
        """UserGroupPermission - a model defined in Swagger"""  # noqa: E501
        self._permission_type = None
        self._security_identity = None
        self.discriminator = None
        if permission_type is not None:
            self.permission_type = permission_type
        if security_identity is not None:
            self.security_identity = security_identity

    @property
    def permission_type(self):
        """Gets the permission_type of this UserGroupPermission.  # noqa: E501


        :return: The permission_type of this UserGroupPermission.  # noqa: E501
        :rtype: GenericPermissions
        """
        return self._permission_type

    @permission_type.setter
    def permission_type(self, permission_type):
        """Sets the permission_type of this UserGroupPermission.


        :param permission_type: The permission_type of this UserGroupPermission.  # noqa: E501
        :type: GenericPermissions
        """

        self._permission_type = permission_type

    @property
    def security_identity(self):
        """Gets the security_identity of this UserGroupPermission.  # noqa: E501


        :return: The security_identity of this UserGroupPermission.  # noqa: E501
        :rtype: str
        """
        return self._security_identity

    @security_identity.setter
    def security_identity(self, security_identity):
        """Sets the security_identity of this UserGroupPermission.


        :param security_identity: The security_identity of this UserGroupPermission.  # noqa: E501
        :type: str
        """

        self._security_identity = security_identity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserGroupPermission, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserGroupPermission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
