# coding: utf-8

"""
    CartoVista REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ValidationErrors(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'common_errors': 'ValidationErrorGroup',
        'fcitc_errors': 'ValidationErrorGroup',
        'trlim_errors': 'ValidationErrorGroup',
        'error_count': 'int'
    }

    attribute_map = {
        'common_errors': 'commonErrors',
        'fcitc_errors': 'fcitcErrors',
        'trlim_errors': 'trlimErrors',
        'error_count': 'errorCount'
    }

    def __init__(self, common_errors=None, fcitc_errors=None, trlim_errors=None, error_count=None):  # noqa: E501
        """ValidationErrors - a model defined in Swagger"""  # noqa: E501
        self._common_errors = None
        self._fcitc_errors = None
        self._trlim_errors = None
        self._error_count = None
        self.discriminator = None
        if common_errors is not None:
            self.common_errors = common_errors
        if fcitc_errors is not None:
            self.fcitc_errors = fcitc_errors
        if trlim_errors is not None:
            self.trlim_errors = trlim_errors
        if error_count is not None:
            self.error_count = error_count

    @property
    def common_errors(self):
        """Gets the common_errors of this ValidationErrors.  # noqa: E501


        :return: The common_errors of this ValidationErrors.  # noqa: E501
        :rtype: ValidationErrorGroup
        """
        return self._common_errors

    @common_errors.setter
    def common_errors(self, common_errors):
        """Sets the common_errors of this ValidationErrors.


        :param common_errors: The common_errors of this ValidationErrors.  # noqa: E501
        :type: ValidationErrorGroup
        """

        self._common_errors = common_errors

    @property
    def fcitc_errors(self):
        """Gets the fcitc_errors of this ValidationErrors.  # noqa: E501


        :return: The fcitc_errors of this ValidationErrors.  # noqa: E501
        :rtype: ValidationErrorGroup
        """
        return self._fcitc_errors

    @fcitc_errors.setter
    def fcitc_errors(self, fcitc_errors):
        """Sets the fcitc_errors of this ValidationErrors.


        :param fcitc_errors: The fcitc_errors of this ValidationErrors.  # noqa: E501
        :type: ValidationErrorGroup
        """

        self._fcitc_errors = fcitc_errors

    @property
    def trlim_errors(self):
        """Gets the trlim_errors of this ValidationErrors.  # noqa: E501


        :return: The trlim_errors of this ValidationErrors.  # noqa: E501
        :rtype: ValidationErrorGroup
        """
        return self._trlim_errors

    @trlim_errors.setter
    def trlim_errors(self, trlim_errors):
        """Sets the trlim_errors of this ValidationErrors.


        :param trlim_errors: The trlim_errors of this ValidationErrors.  # noqa: E501
        :type: ValidationErrorGroup
        """

        self._trlim_errors = trlim_errors

    @property
    def error_count(self):
        """Gets the error_count of this ValidationErrors.  # noqa: E501


        :return: The error_count of this ValidationErrors.  # noqa: E501
        :rtype: int
        """
        return self._error_count

    @error_count.setter
    def error_count(self, error_count):
        """Sets the error_count of this ValidationErrors.


        :param error_count: The error_count of this ValidationErrors.  # noqa: E501
        :type: int
        """

        self._error_count = error_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValidationErrors, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValidationErrors):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
